/**
 * HackHub Authoritative Canonical API Route Registry
 * 
 * Every route in the platform must be registered here.
 * Structure:
 * - method: HTTP Method (GET, POST, PATCH, DELETE)
 * - path: Canonical path starting with /api/
 * - domain: Domain classification
 * - auth: Boolean, authentication required
 * - roles: Allowed user roles (or null if public or any role)
 * - params: Array of URL parameter keys
 * - controller: Controller handler identifier
 * - service: Backing service identifier
 * - purpose: Concise description of operation
 */

export const CANONICAL_ROUTES = [
  // ================= HEALTH =================
  {
    method: 'GET',
    path: '/api/health',
    domain: 'HEALTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'HealthController.checkHealth',
    service: 'HealthService.checkHealth',
    purpose: 'API service liveness and database connection status',
  },

  // ================= AUTH =================
  {
    method: 'POST',
    path: '/api/auth/register',
    domain: 'AUTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'AuthController.register',
    service: 'AuthService.register',
    purpose: 'Register new participant user account and initialize profile',
  },
  {
    method: 'POST',
    path: '/api/auth/verify-email',
    domain: 'AUTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'AuthController.verifyEmail',
    service: 'AuthService.verifyEmail',
    purpose: 'Verify user email address with verification token',
  },
  {
    method: 'POST',
    path: '/api/auth/login',
    domain: 'AUTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'AuthController.login',
    service: 'AuthService.login',
    purpose: 'Authenticate user credentials, return JWT token and create session',
  },
  {
    method: 'POST',
    path: '/api/auth/forgot-password',
    domain: 'AUTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'AuthController.forgotPassword',
    service: 'AuthService.forgotPassword',
    purpose: 'Initiate password reset request and email token',
  },
  {
    method: 'POST',
    path: '/api/auth/reset-password',
    domain: 'AUTH',
    auth: false,
    roles: null,
    params: [],
    controller: 'AuthController.resetPassword',
    service: 'AuthService.resetPassword',
    purpose: 'Complete password reset using secure token',
  },
  {
    method: 'GET',
    path: '/api/auth/me',
    domain: 'AUTH',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'AuthController.getMe',
    service: 'AuthService.getMe',
    purpose: 'Get authenticated user context, profile summary, teams, and reputation',
  },
  {
    method: 'POST',
    path: '/api/auth/logout',
    domain: 'AUTH',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'AuthController.logout',
    service: 'AuthService.logout',
    purpose: 'Invalidate current session and revoke tokens',
  },
  {
    method: 'POST',
    path: '/api/auth/change-password',
    domain: 'AUTH',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'AuthController.changePassword',
    service: 'AuthService.changePassword',
    purpose: 'Update authenticated user account password',
  },
  {
    method: 'POST',
    path: '/api/auth/invitations',
    domain: 'AUTH',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'AuthController.createStaffInvitation',
    service: 'AuthService.createStaffInvitation',
    purpose: 'Invite new judge or mentor staff member to the platform',
  },
  {
    method: 'POST',
    path: '/api/auth/invitations/:invitationId/accept',
    domain: 'AUTH',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['invitationId'],
    controller: 'AuthController.acceptStaffInvitation',
    service: 'AuthService.acceptStaffInvitation',
    purpose: 'Accept platform staff invitation and elevate user role',
  },
  {
    method: 'DELETE',
    path: '/api/auth/invitations/:invitationId',
    domain: 'AUTH',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['invitationId'],
    controller: 'AuthController.revokeStaffInvitation',
    service: 'AuthService.revokeStaffInvitation',
    purpose: 'Revoke pending platform staff invitation',
  },

  // ================= EVENTS =================
  {
    method: 'GET',
    path: '/api/events',
    domain: 'EVENTS',
    auth: false,
    roles: null,
    params: [],
    controller: 'EventController.listEvents',
    service: 'EventService.listEvents',
    purpose: 'List published and active hackathons with optional category/search filters',
  },
  {
    method: 'GET',
    path: '/api/events/:eventId',
    domain: 'EVENTS',
    auth: false,
    roles: null,
    params: ['eventId'],
    controller: 'EventController.getEventById',
    service: 'EventService.getEventById',
    purpose: 'Get comprehensive event details, track challenges, and active rubric',
  },
  {
    method: 'POST',
    path: '/api/events',
    domain: 'EVENTS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'EventController.createEvent',
    service: 'EventService.createEvent',
    purpose: 'Create new hackathon event (defaults to draft status)',
  },
  {
    method: 'PATCH',
    path: '/api/events/:eventId',
    domain: 'EVENTS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'EventController.updateEvent',
    service: 'EventService.updateEvent',
    purpose: 'Update event metadata, schedule dates, or settings',
  },
  {
    method: 'POST',
    path: '/api/events/:eventId/publish',
    domain: 'EVENTS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'EventController.publishEvent',
    service: 'EventService.publishEvent',
    purpose: 'Transition draft event to published status for public discovery',
  },
  {
    method: 'POST',
    path: '/api/events/:eventId/lock-submissions',
    domain: 'EVENTS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'EventController.lockSubmissions',
    service: 'EventService.lockSubmissions',
    purpose: 'Officially lock submissions window for an event',
  },
  {
    method: 'GET',
    path: '/api/events/:eventId/challenges',
    domain: 'EVENTS',
    auth: false,
    roles: null,
    params: ['eventId'],
    controller: 'ChallengeController.listChallenges',
    service: 'ChallengeService.listChallenges',
    purpose: 'List challenge tracks associated with a specific event',
  },
  {
    method: 'PATCH',
    path: '/api/events/:eventId/assignments',
    domain: 'EVENTS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'EventController.assignStaff',
    service: 'EventService.assignStaff',
    purpose: 'Assign mentors or judges to event submissions and teams',
  },

  // ================= CHALLENGES =================
  {
    method: 'GET',
    path: '/api/events/:eventId/challenges/:challengeId',
    domain: 'CHALLENGES',
    auth: false,
    roles: null,
    params: ['eventId', 'challengeId'],
    controller: 'ChallengeController.getChallengeById',
    service: 'ChallengeService.getChallengeById',
    purpose: 'Get specific challenge problem statement, requirements, and tags',
  },
  {
    method: 'POST',
    path: '/api/events/:eventId/challenges',
    domain: 'CHALLENGES',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'ChallengeController.createChallenge',
    service: 'ChallengeService.createChallenge',
    purpose: 'Create new challenge problem statement under an event',
  },
  {
    method: 'PATCH',
    path: '/api/challenges/:challengeId',
    domain: 'CHALLENGES',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['challengeId'],
    controller: 'ChallengeController.updateChallenge',
    service: 'ChallengeService.updateChallenge',
    purpose: 'Update challenge details, requirements, or skills',
  },

  // ================= PROFILES =================
  {
    method: 'GET',
    path: '/api/profiles/me',
    domain: 'PROFILES',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'ProfileController.getMyProfile',
    service: 'ProfileService.getMyProfile',
    purpose: 'Retrieve authenticated user detailed profile',
  },
  {
    method: 'PATCH',
    path: '/api/profiles/me',
    domain: 'PROFILES',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'ProfileController.updateMyProfile',
    service: 'ProfileService.updateMyProfile',
    purpose: 'Update user profile bio, skills, availability, and discoveryConsent',
  },

  // ================= DISCOVERY =================
  {
    method: 'POST',
    path: '/api/discovery/challenges',
    domain: 'DISCOVERY',
    auth: false,
    roles: null,
    params: [],
    controller: 'DiscoveryController.discoverChallenges',
    service: 'DiscoveryService.discoverChallenges',
    purpose: 'Filter and search challenges by difficulty, tags, or keywords',
  },
  {
    method: 'POST',
    path: '/api/discovery/teammates',
    domain: 'DISCOVERY',
    auth: true,
    roles: ['PARTICIPANT', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'DiscoveryController.discoverTeammates',
    service: 'DiscoveryService.discoverTeammates',
    purpose: 'Discover candidate teammates respecting discoveryConsent === true',
  },

  // ================= TEAMS =================
  {
    method: 'POST',
    path: '/api/teams',
    domain: 'TEAMS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: [],
    controller: 'TeamController.createTeam',
    service: 'TeamService.createTeam',
    purpose: 'Create new team within an event and assign creator as captain',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId',
    domain: 'TEAMS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'TeamController.getTeamById',
    service: 'TeamService.getTeamById',
    purpose: 'Get team workspace summary, challenge, decisions, and progress',
  },
  {
    method: 'PATCH',
    path: '/api/teams/:teamId',
    domain: 'TEAMS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'TeamController.updateTeam',
    service: 'TeamService.updateTeam',
    purpose: 'Update team name, description, or technical decisions (captain only)',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId/members',
    domain: 'MEMBERSHIP',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'TeamController.getTeamMembers',
    service: 'TeamService.getTeamMembers',
    purpose: 'List active members of a team with roles and responsibilities',
  },

  // ================= JOIN REQUESTS =================
  {
    method: 'POST',
    path: '/api/teams/:teamId/join-requests',
    domain: 'JOIN REQUESTS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'JoinRequestController.createJoinRequest',
    service: 'JoinRequestService.createJoinRequest',
    purpose: 'Submit join request to a team (prevents duplicate pending requests)',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId/join-requests',
    domain: 'JOIN REQUESTS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'JoinRequestController.getTeamJoinRequests',
    service: 'JoinRequestService.getTeamJoinRequests',
    purpose: 'List pending join requests for a team (captain only)',
  },
  {
    method: 'POST',
    path: '/api/join-requests/:requestId/accept',
    domain: 'JOIN REQUESTS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['requestId'],
    controller: 'JoinRequestController.acceptJoinRequest',
    service: 'JoinRequestService.acceptJoinRequest',
    purpose: 'Accept join request and create active Membership record',
  },
  {
    method: 'POST',
    path: '/api/join-requests/:requestId/reject',
    domain: 'JOIN REQUESTS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['requestId'],
    controller: 'JoinRequestController.rejectJoinRequest',
    service: 'JoinRequestService.rejectJoinRequest',
    purpose: 'Reject pending team join request',
  },
  {
    method: 'DELETE',
    path: '/api/join-requests/:requestId',
    domain: 'JOIN REQUESTS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['requestId'],
    controller: 'JoinRequestController.cancelJoinRequest',
    service: 'JoinRequestService.cancelJoinRequest',
    purpose: 'Cancel or withdraw pending join request',
  },

  // ================= INVITATIONS =================
  {
    method: 'POST',
    path: '/api/teams/:teamId/invitations',
    domain: 'INVITATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'InvitationController.createInvitation',
    service: 'InvitationService.createInvitation',
    purpose: 'Send team invitation to a candidate (prevents duplicate pending)',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId/invitations',
    domain: 'INVITATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'InvitationController.getTeamInvitations',
    service: 'InvitationService.getTeamInvitations',
    purpose: 'Get sent invitations for a team (captain only)',
  },
  {
    method: 'POST',
    path: '/api/invitations/:invitationId/accept',
    domain: 'INVITATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['invitationId'],
    controller: 'InvitationController.acceptInvitation',
    service: 'InvitationService.acceptInvitation',
    purpose: 'Accept team invitation and become active member',
  },
  {
    method: 'POST',
    path: '/api/invitations/:invitationId/reject',
    domain: 'INVITATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['invitationId'],
    controller: 'InvitationController.rejectInvitation',
    service: 'InvitationService.rejectInvitation',
    purpose: 'Decline team invitation',
  },
  {
    method: 'DELETE',
    path: '/api/invitations/:invitationId',
    domain: 'INVITATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['invitationId'],
    controller: 'InvitationController.cancelInvitation',
    service: 'InvitationService.cancelInvitation',
    purpose: 'Cancel sent team invitation',
  },

  // ================= TASKS =================
  {
    method: 'GET',
    path: '/api/teams/:teamId/tasks',
    domain: 'TASKS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'TaskController.getTeamTasks',
    service: 'TaskService.getTeamTasks',
    purpose: 'List Kanban sprint tasks for team',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/tasks',
    domain: 'TASKS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'TaskController.createTask',
    service: 'TaskService.createTask',
    purpose: 'Create new task in team sprint Kanban board',
  },
  {
    method: 'GET',
    path: '/api/tasks/:taskId',
    domain: 'TASKS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'ORGANIZER', 'ADMIN'],
    params: ['taskId'],
    controller: 'TaskController.getTaskById',
    service: 'TaskService.getTaskById',
    purpose: 'Get specific task details and history',
  },
  {
    method: 'PATCH',
    path: '/api/tasks/:taskId',
    domain: 'TASKS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['taskId'],
    controller: 'TaskController.updateTask',
    service: 'TaskService.updateTask',
    purpose: 'Update task with optimistic concurrency (version check -> 409 if conflict)',
  },
  {
    method: 'DELETE',
    path: '/api/tasks/:taskId',
    domain: 'TASKS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['taskId'],
    controller: 'TaskController.deleteTask',
    service: 'TaskService.deleteTask',
    purpose: 'Delete task from team Kanban board',
  },

  // ================= MILESTONES =================
  {
    method: 'GET',
    path: '/api/teams/:teamId/milestones',
    domain: 'MILESTONES',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'MilestoneController.getTeamMilestones',
    service: 'MilestoneService.getTeamMilestones',
    purpose: 'List milestones and completion percentages for team',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/milestones',
    domain: 'MILESTONES',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'MilestoneController.createMilestone',
    service: 'MilestoneService.createMilestone',
    purpose: 'Create new project milestone with target date',
  },
  {
    method: 'PATCH',
    path: '/api/milestones/:milestoneId',
    domain: 'MILESTONES',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['milestoneId'],
    controller: 'MilestoneController.updateMilestone',
    service: 'MilestoneService.updateMilestone',
    purpose: 'Update milestone status, description, or completion percentage',
  },
  {
    method: 'DELETE',
    path: '/api/milestones/:milestoneId',
    domain: 'MILESTONES',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['milestoneId'],
    controller: 'MilestoneController.deleteMilestone',
    service: 'MilestoneService.deleteMilestone',
    purpose: 'Remove milestone from project plan (captain only)',
  },

  // ================= SUBMISSIONS =================
  {
    method: 'GET',
    path: '/api/teams/:teamId/checklist',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'SubmissionController.getSubmissionChecklist',
    service: 'SubmissionService.getSubmissionChecklist',
    purpose: 'Get dynamically derived submission readiness % and deadline status',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId/submission',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'SubmissionController.getTeamSubmission',
    service: 'SubmissionService.getTeamSubmission',
    purpose: 'Get submission draft or final submission details for team',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/submission',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'SubmissionController.upsertSubmission',
    service: 'SubmissionService.upsertSubmission',
    purpose: 'Save draft or submit final project (enforces server-side deadline)',
  },
  {
    method: 'PATCH',
    path: '/api/teams/:teamId/submission',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'SubmissionController.updateSubmissionDraft',
    service: 'SubmissionService.updateSubmissionDraft',
    purpose: 'Patch submission draft fields before deadline',
  },
  {
    method: 'GET',
    path: '/api/submissions/:submissionId',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['submissionId'],
    controller: 'SubmissionController.getSubmissionById',
    service: 'SubmissionService.getSubmissionById',
    purpose: 'Get submission details by direct submission ID',
  },
  {
    method: 'POST',
    path: '/api/submissions/:submissionId/submit',
    domain: 'SUBMISSIONS',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['submissionId'],
    controller: 'SubmissionController.submitFinalSubmission',
    service: 'SubmissionService.submitFinalSubmission',
    purpose: 'Finalize and lock project submission before event deadline',
  },

  // ================= RUBRICS =================
  {
    method: 'GET',
    path: '/api/events/:eventId/rubric',
    domain: 'RUBRICS',
    auth: false,
    roles: null,
    params: ['eventId'],
    controller: 'RubricController.getEventRubric',
    service: 'RubricService.getEventRubric',
    purpose: 'Get active versioned rubric and criteria for an event',
  },
  {
    method: 'GET',
    path: '/api/rubrics/:rubricId',
    domain: 'RUBRICS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['rubricId'],
    controller: 'RubricController.getRubricById',
    service: 'RubricService.getRubricById',
    purpose: 'Get rubric by unique rubric ID',
  },
  {
    method: 'POST',
    path: '/api/events/:eventId/rubric',
    domain: 'RUBRICS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'RubricController.createRubric',
    service: 'RubricService.createRubric',
    purpose: 'Create new versioned evaluation rubric for an event',
  },
  {
    method: 'PATCH',
    path: '/api/rubrics/:rubricId',
    domain: 'RUBRICS',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['rubricId'],
    controller: 'RubricController.updateRubric',
    service: 'RubricService.updateRubric',
    purpose: 'Update rubric criteria and scoring weights',
  },

  // ================= MENTOR =================
  {
    method: 'GET',
    path: '/api/mentor/teams',
    domain: 'MENTOR',
    auth: true,
    roles: ['MENTOR', 'ADMIN'],
    params: [],
    controller: 'MentorController.getAssignedTeams',
    service: 'MentorService.getAssignedTeams',
    purpose: 'List teams assigned to current authenticated mentor',
  },
  {
    method: 'GET',
    path: '/api/teams/:teamId/feedback',
    domain: 'MENTOR',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'ORGANIZER', 'ADMIN'],
    params: ['teamId'],
    controller: 'MentorController.getTeamFeedback',
    service: 'MentorService.getTeamFeedback',
    purpose: 'List mentor guidance and feedback records for a team',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/feedback',
    domain: 'MENTOR',
    auth: true,
    roles: ['MENTOR', 'ADMIN'],
    params: ['teamId'],
    controller: 'MentorController.createFeedback',
    service: 'MentorService.createFeedback',
    purpose: 'Post actionable mentor feedback and recommendations',
  },

  // ================= JUDGE =================
  {
    method: 'GET',
    path: '/api/judge/submissions',
    domain: 'JUDGE',
    auth: true,
    roles: ['JUDGE', 'ADMIN'],
    params: [],
    controller: 'JudgeController.getAssignedSubmissions',
    service: 'JudgeService.getAssignedSubmissions',
    purpose: 'List event submissions assigned to judge for evaluation',
  },
  {
    method: 'GET',
    path: '/api/submissions/:submissionId/scores',
    domain: 'JUDGE',
    auth: true,
    roles: ['JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['submissionId'],
    controller: 'JudgeController.getSubmissionScores',
    service: 'JudgeService.getSubmissionScores',
    purpose: 'Retrieve recorded evaluation scores for a submission',
  },
  {
    method: 'POST',
    path: '/api/submissions/:submissionId/scores',
    domain: 'JUDGE',
    auth: true,
    roles: ['JUDGE', 'ADMIN'],
    params: ['submissionId'],
    controller: 'JudgeController.submitScore',
    service: 'JudgeService.submitScore',
    purpose: 'Submit 100-point rubric evaluation score (prohibits self-team scoring)',
  },

  // ================= ORGANIZER =================
  {
    method: 'GET',
    path: '/api/organizer/events',
    domain: 'ORGANIZER',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'OrganizerController.getOrganizerEvents',
    service: 'OrganizerService.getOrganizerEvents',
    purpose: 'List hackathon events organized by authenticated user',
  },
  {
    method: 'GET',
    path: '/api/organizer/events/:eventId',
    domain: 'ORGANIZER',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'OrganizerController.getOrganizerEventDetails',
    service: 'OrganizerService.getOrganizerEventDetails',
    purpose: 'Get comprehensive organizer metrics, submissions tally, and disputes',
  },

  // ================= DOCUMENTS / RULEBOOK =================
  {
    method: 'POST',
    path: '/api/events/:eventId/documents',
    domain: 'DOCUMENTS / RULEBOOK',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'DocumentController.uploadDocument',
    service: 'DocumentService.uploadDocument',
    purpose: 'Upload new rulebook PDF or markdown document for ingestion',
  },
  {
    method: 'GET',
    path: '/api/events/:eventId/documents',
    domain: 'DOCUMENTS / RULEBOOK',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'DocumentController.getEventDocuments',
    service: 'DocumentService.getEventDocuments',
    purpose: 'List rulebook documents uploaded for an event',
  },
  {
    method: 'GET',
    path: '/api/documents/:documentId',
    domain: 'DOCUMENTS / RULEBOOK',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['documentId'],
    controller: 'DocumentController.getDocumentById',
    service: 'DocumentService.getDocumentById',
    purpose: 'Get document details, chunk count, and processing state',
  },
  {
    method: 'POST',
    path: '/api/documents/:documentId/retry',
    domain: 'DOCUMENTS / RULEBOOK',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['documentId'],
    controller: 'DocumentController.retryDocumentProcessing',
    service: 'DocumentService.retryDocumentProcessing',
    purpose: 'Retry extraction and embedding pipeline for failed document',
  },
  {
    method: 'DELETE',
    path: '/api/documents/:documentId',
    domain: 'DOCUMENTS / RULEBOOK',
    auth: true,
    roles: ['ORGANIZER', 'ADMIN'],
    params: ['documentId'],
    controller: 'DocumentController.deleteDocument',
    service: 'DocumentService.deleteDocument',
    purpose: 'Delete document and cascade remove all parsed chunks',
  },

  // ================= RAG / RULEBOOK Q&A =================
  {
    method: 'POST',
    path: '/api/events/:eventId/rulebook/query',
    domain: 'RAG',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['eventId'],
    controller: 'RagController.queryRulebook',
    service: 'RagService.queryRulebook',
    purpose: 'Query event rulebook with strict event-scoped chunk retrieval and citations',
  },

  // ================= AI DELIVERY PLANNER =================
  {
    method: 'POST',
    path: '/api/teams/:teamId/ai/delivery-plan',
    domain: 'AI DELIVERY PLANNER',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId'],
    controller: 'AgentController.generateDeliveryPlan',
    service: 'AgentService.generateDeliveryPlan',
    purpose: 'Generate read-only delivery assessment and proposed milestones via AgentRun',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/ai/delivery-plan/:agentRunId/confirm',
    domain: 'AI DELIVERY PLANNER',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId', 'agentRunId'],
    controller: 'AgentController.confirmDeliveryPlan',
    service: 'AgentService.confirmDeliveryPlan',
    purpose: 'Captain confirms and applies approved milestones into team plan',
  },
  {
    method: 'POST',
    path: '/api/teams/:teamId/ai/delivery-plan/:agentRunId/cancel',
    domain: 'AI DELIVERY PLANNER',
    auth: true,
    roles: ['PARTICIPANT', 'ADMIN'],
    params: ['teamId', 'agentRunId'],
    controller: 'AgentController.cancelDeliveryPlan',
    service: 'AgentService.cancelDeliveryPlan',
    purpose: 'Reject and discard proposed delivery plan proposal',
  },

  // ================= NOTIFICATIONS =================
  {
    method: 'GET',
    path: '/api/notifications',
    domain: 'NOTIFICATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'NotificationController.getMyNotifications',
    service: 'NotificationService.getMyNotifications',
    purpose: 'List notifications for current user with unread counts',
  },
  {
    method: 'PATCH',
    path: '/api/notifications/:notificationId/read',
    domain: 'NOTIFICATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['notificationId'],
    controller: 'NotificationController.markNotificationRead',
    service: 'NotificationService.markNotificationRead',
    purpose: 'Mark specific notification as read (PATCH)',
  },
  {
    method: 'POST',
    path: '/api/notifications/:notificationId/read',
    domain: 'NOTIFICATIONS',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['notificationId'],
    controller: 'NotificationController.markNotificationRead',
    service: 'NotificationService.markNotificationRead',
    purpose: 'Mark specific notification as read (POST alias)',
  },

  // ================= REPUTATION =================
  {
    method: 'GET',
    path: '/api/reputation/me',
    domain: 'REPUTATION',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: [],
    controller: 'ReputationController.getMyReputation',
    service: 'ReputationService.getMyReputation',
    purpose: 'Get aggregated reputation score and points history for current user',
  },
  {
    method: 'GET',
    path: '/api/users/:userId/reputation',
    domain: 'REPUTATION',
    auth: true,
    roles: ['PARTICIPANT', 'MENTOR', 'JUDGE', 'ORGANIZER', 'ADMIN'],
    params: ['userId'],
    controller: 'ReputationController.getUserReputation',
    service: 'ReputationService.getUserReputation',
    purpose: 'Get public reputation points and ledger history for any user',
  },
];

export const getRoutesByDomain = (domain) => {
  return CANONICAL_ROUTES.filter((r) => r.domain === domain);
};

export const findRoute = (method, path) => {
  return CANONICAL_ROUTES.find(
    (r) => r.method.toUpperCase() === method.toUpperCase() && r.path === path
  );
};

export default CANONICAL_ROUTES;
