import mongoose from 'mongoose';

// Deterministic ObjectIds
export const IDS = {
  users: {
    karthik: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60001'),
    rahul: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60002'),
    ananya: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60003'),
    vivek: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60004'),
    aakash: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60005'), // Organizer
    arvind: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60006'), // Mentor
    siddharth: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60007'), // Judge
  },
  profiles: {
    karthik: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60011'),
    rahul: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60012'),
    ananya: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60013'),
    vivek: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60014'),
  },
  event: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60020'), // NexusHack 2026
  challenges: {
    studyEngine: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60031'),
    smartCampus: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60032'),
    telehealth: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60033'),
  },
  team: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60040'), // Team Nova
  memberships: {
    karthik: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60051'),
    rahul: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60052'),
    ananya: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60053'),
    vivek: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60054'),
  },
  rubric: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60060'),
  submission: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60070'),
  tasks: [
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60081'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60082'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60083'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60084'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60085'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60086'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60087'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60088'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60089'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f6008a'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f6008b'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f6008c'),
  ],
  milestones: [
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60091'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60092'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60093'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60094'),
    new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60095'),
  ],
  document: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f600e1'),
  agentRun: new mongoose.Types.ObjectId('67039a00b1a2c3d4e5f60101'),
};

export const seedUsers = [
  {
    _id: IDS.users.karthik,
    name: 'Karthik',
    email: 'karthik.dev@college.edu',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'PARTICIPANT',
    college: 'National Institute of Technology',
    graduationYear: '3rd Year, B.Tech CSE',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.rahul,
    name: 'Rahul Sharma',
    email: 'rahul.sharma@college.edu',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'PARTICIPANT',
    college: 'IIT Bombay',
    graduationYear: '3rd Year',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.ananya,
    name: 'Ananya Iyer',
    email: 'ananya.iyer@college.edu',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'PARTICIPANT',
    college: 'BITS Pilani',
    graduationYear: '4th Year',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.vivek,
    name: 'Vivek Patel',
    email: 'vivek.patel@college.edu',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'PARTICIPANT',
    college: 'IIIT Hyderabad',
    graduationYear: '3rd Year',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.aakash,
    name: 'Aakash Mehta',
    email: 'aakash.organizer@nexushack.org',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'ORGANIZER',
    college: 'National Institute of Technology',
    graduationYear: 'Alumni',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.arvind,
    name: 'Dr. Arvind Rao',
    email: 'arvind.rao@faculty.edu',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'MENTOR',
    college: 'National Institute of Technology',
    graduationYear: 'Faculty',
    isActive: true,
    emailVerified: true,
  },
  {
    _id: IDS.users.siddharth,
    name: 'Siddharth Sen',
    email: 'siddharth.judge@techlead.io',
    passwordHash: '$2b$12$eOqJ2p0uR1N54kX6bK0Y7.0P7k5Wk5Wk5Wk5Wk5Wk5Wk5Wk5Wk5W',
    role: 'JUDGE',
    college: 'Industry Partner',
    graduationYear: 'Senior Tech Lead',
    isActive: true,
    emailVerified: true,
  },
];

export const seedProfiles = [
  {
    _id: IDS.profiles.karthik,
    userId: IDS.users.karthik,
    bio: 'Pre-final year CS student passionate about distributed systems, clean REST architectures, and developer tooling. Looking to build high-impact hackathon solutions.',
    specialization: 'Backend Developer',
    skills: ['Node.js', 'MongoDB', 'Express', 'Java', 'Python', 'Redis', 'PostgreSQL', 'Docker', 'Git'],
    interests: ['AI', 'Hackathons', 'Web Development', 'Developer Tools', 'Cloud Systems'],
    experienceLevel: 'advanced',
    availability: '8-10 hrs/week',
    discoveryConsent: true,
    codingProfiles: {
      github: 'https://github.com/karthik-dev',
      leetcode: 'https://leetcode.com/karthik_code',
    },
    projects: [
      {
        title: 'AI Study Planner',
        description: 'Generates tailored revision roadmaps based on syllabus PDF analysis and user availability.',
        techStack: ['Node.js', 'Express', 'OpenAI API', 'MongoDB'],
        githubUrl: 'https://github.com/karthik-dev/ai-study-planner',
        liveUrl: 'https://study-planner-demo.vercel.app',
      },
    ],
  },
  {
    _id: IDS.profiles.rahul,
    userId: IDS.users.rahul,
    bio: 'Passionate React & Next.js frontend dev. Love crafting crisp, responsive interfaces with clean Tailwind & micro-interactions.',
    specialization: 'Frontend Developer',
    skills: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Redux Toolkit', 'Figma'],
    interests: ['AI', 'Healthcare', 'EdTech', 'Web3'],
    experienceLevel: 'advanced',
    availability: '8 hrs/week',
    discoveryConsent: true,
    codingProfiles: {
      github: 'https://github.com/rahul-sharma-dev',
      leetcode: 'https://leetcode.com/rahul_fe',
    },
  },
  {
    _id: IDS.profiles.ananya,
    userId: IDS.users.ananya,
    bio: 'Human-centered product designer. Specialized in rapid wireframing, design systems, usability research, and frontend translation in React.',
    specialization: 'UI/UX Designer',
    skills: ['Figma', 'Design Systems', 'Tailwind CSS', 'Wireframing', 'User Research', 'Prototyping'],
    interests: ['FinTech', 'Accessibility', 'Open Innovation', 'Developer Tools'],
    experienceLevel: 'expert',
    availability: '10 hrs/week',
    discoveryConsent: true,
    codingProfiles: {
      github: 'https://github.com/ananya-designs',
    },
  },
  {
    _id: IDS.profiles.vivek,
    userId: IDS.users.vivek,
    bio: 'Specializing in LangChain RAG pipelines, fine-tuning lightweight SLMs, PyTorch, and multimodal agent workflows.',
    specialization: 'AI/ML Developer',
    skills: ['Python', 'PyTorch', 'Hugging Face', 'LangChain', 'FastAPI', 'Vector DBs'],
    interests: ['AI', 'Generative AI', 'Computer Vision', 'Robotics'],
    experienceLevel: 'advanced',
    availability: '12 hrs/week',
    discoveryConsent: true,
    codingProfiles: {
      github: 'https://github.com/vivek-ai-hub',
      leetcode: 'https://leetcode.com/vivek_ml',
    },
  },
];

export const seedEvent = {
  _id: IDS.event,
  name: 'NexusHack 2026: AI & Intelligent Systems',
  slug: 'nexushack-2026',
  organizerId: IDS.users.aakash,
  organizerName: 'ACM Student Chapter & IEEE',
  description: 'A 48-hour intensive hackathon uniting engineers, designers, and AI researchers to build practical, production-ready intelligent workflows solving campus, healthcare, and education bottlenecks.',
  theme: 'AI & Intelligent Systems',
  categories: ['AI', 'Web', 'Cloud', 'Healthcare', 'IoT'],
  technologies: ['React', 'Node.js', 'Python', 'MongoDB', 'FastAPI', 'Docker'],
  mode: 'hybrid',
  location: 'National Institute of Technology (Hybrid)',
  prizePool: '₹2,50,000',
  minTeamSize: 2,
  maxTeamSize: 4,
  registrationDeadline: new Date('2026-10-10T23:59:59.000Z'),
  startDate: new Date('2026-10-12T09:00:00.000Z'),
  endDate: new Date('2026-10-14T23:59:59.000Z'),
  submissionDeadline: new Date('2026-10-14T23:59:00.000Z'), // Official deadline in MongoDB
  status: 'active',
  bannerGradient: 'from-indigo-600 to-blue-700',
};

export const seedChallenges = [
  {
    _id: IDS.challenges.studyEngine,
    eventId: IDS.event,
    title: 'Intelligent Adaptive Study Engine',
    track: 'AI & Education',
    problemStatement: 'College students struggle with unstructured textbook PDFs, syllabus revisions, and exam stress without targeted micro-learning paths.',
    description: 'Build an AI-powered assistant that ingests course syllabi and lecture slides, analyzes student weaknesses through quick diagnostic tests, and dynamically generates actionable daily study sprints with automated quizzes.',
    category: 'AI',
    difficulty: 'advanced',
    requirements: [
      'Interactive student dashboard for subject syllabus tracking',
      'Automated question generator from document context',
      'Progress and knowledge retention analytics',
      'Clean responsive UI with zero clutter',
    ],
    technologies: ['React', 'Tailwind CSS', 'Node.js', 'Python', 'LangChain', 'MongoDB'],
    recommendedSkills: ['React', 'Tailwind CSS', 'Node.js', 'Python', 'MongoDB'],
    maxScore: 100,
    deadline: new Date('2026-10-14T23:59:00.000Z'),
  },
  {
    _id: IDS.challenges.smartCampus,
    eventId: IDS.event,
    title: 'Campus Resource & Energy Optimization',
    track: 'IoT & Web',
    problemStatement: 'High energy wastage in university labs, unmonitored classroom electricity usage, and chaotic library seating availability.',
    description: 'Develop a live telemetry dashboard and smart booking portal that aggregates simulated IoT sensor feeds to automate lab equipment scheduling and energy consumption insights.',
    category: 'IoT',
    difficulty: 'intermediate',
    requirements: [
      'Real-time sensor telemetry visualizer (power consumption & room occupancy)',
      'Room/lab seat reservation workflow with collision prevention',
      'Predictive peak-hour electricity usage alerts',
    ],
    technologies: ['React', 'FastAPI', 'Node.js', 'MQTT', 'WebSockets', 'PostgreSQL'],
    recommendedSkills: ['React', 'FastAPI', 'MQTT', 'WebSockets'],
    maxScore: 100,
    deadline: new Date('2026-10-14T23:59:00.000Z'),
  },
  {
    _id: IDS.challenges.telehealth,
    eventId: IDS.event,
    title: 'Rural Tele-Triage & Diagnostic Assistant',
    track: 'Healthcare & AI',
    problemStatement: 'Primary healthcare clinics in remote locations face acute shortages of specialists and structured patient triage systems.',
    description: 'Create a lightweight, offline-resilient digital triage web app allowing community health workers to record patient vitals, receive AI-assisted symptom stratification, and queue priority tele-consultations.',
    category: 'Healthcare',
    difficulty: 'intermediate',
    requirements: [
      'Offline-first patient data capture',
      'Visual symptom selector and risk assessment matrix',
      'Secure doctor dashboard with exportable medical summaries',
    ],
    technologies: ['React', 'TypeScript', 'Node.js', 'IndexedDB', 'Tailwind CSS'],
    recommendedSkills: ['React', 'TypeScript', 'Node.js', 'IndexedDB'],
    maxScore: 100,
    deadline: new Date('2026-10-14T23:59:00.000Z'),
  },
];

export const seedTeam = {
  _id: IDS.team,
  eventId: IDS.event,
  challengeId: IDS.challenges.studyEngine,
  name: 'Team Nova',
  description: 'Building an AI-driven adaptive syllabus roadmap and automated quiz diagnostic platform.',
  createdBy: IDS.users.karthik,
  status: 'active',
  technicalDecisions: [
    {
      id: 'td1',
      title: 'Adopt Tailwind CSS for Rapid UI Consistency',
      author: 'Ananya Iyer',
      date: '2 days ago',
      status: 'Approved',
    },
    {
      id: 'td2',
      title: 'Use Local Vector Embeddings (FastAPI) to avoid API latency',
      author: 'Vivek Patel',
      date: 'Yesterday',
      status: 'Approved',
    },
    {
      id: 'td3',
      title: 'Deploy Backend on Render and Frontend on Vercel',
      author: 'Karthik',
      date: 'Today',
      status: 'In Discussion',
    },
  ],
};

export const seedMemberships = [
  {
    _id: IDS.memberships.karthik,
    userId: IDS.users.karthik,
    teamId: IDS.team,
    eventId: IDS.event,
    role: 'captain',
    status: 'active',
    responsibilities: ['System Architecture', 'Backend REST Endpoints', 'Database Indexing'],
    specialization: 'Backend Developer',
  },
  {
    _id: IDS.memberships.rahul,
    userId: IDS.users.rahul,
    teamId: IDS.team,
    eventId: IDS.event,
    role: 'member',
    status: 'active',
    responsibilities: ['React UI Components', 'Tailwind Micro-interactions', 'State Management'],
    specialization: 'Frontend Developer',
  },
  {
    _id: IDS.memberships.ananya,
    userId: IDS.users.ananya,
    teamId: IDS.team,
    eventId: IDS.event,
    role: 'member',
    status: 'active',
    responsibilities: ['UI/UX Design Systems', 'Figma Prototyping', 'Accessibility Audit'],
    specialization: 'UI/UX Designer',
  },
  {
    _id: IDS.memberships.vivek,
    userId: IDS.users.vivek,
    teamId: IDS.team,
    eventId: IDS.event,
    role: 'member',
    status: 'active',
    responsibilities: ['LangChain RAG Pipeline', 'FastAPI Vector Search', 'Prompt Engineering'],
    specialization: 'AI/ML Developer',
  },
];

export const seedRubric = {
  _id: IDS.rubric,
  eventId: IDS.event,
  version: 1,
  totalMaxScore: 100,
  createdBy: IDS.users.aakash,
  isActive: true,
  criteria: [
    {
      criterionId: 'crit_innovation',
      name: 'Innovation & Originality',
      description: 'Novelty of approach and real-world problem relevance.',
      maxScore: 25,
      weightPercentage: 25,
      requiredEvidence: 'Problem statement and architecture breakdown',
    },
    {
      criterionId: 'crit_technical',
      name: 'Technical Execution',
      description: 'Architecture cleanliness, code quality, stability, and proper API design.',
      maxScore: 30,
      weightPercentage: 30,
      requiredEvidence: 'Public GitHub repository and working endpoints',
    },
    {
      criterionId: 'crit_ux',
      name: 'UI/UX & Accessibility',
      description: 'Intuitive user journeys, responsive design, and visual polish.',
      maxScore: 20,
      weightPercentage: 20,
      requiredEvidence: 'Live web deployment and responsive screenshots',
    },
    {
      criterionId: 'crit_impact',
      name: 'Impact & Feasibility',
      description: 'Practical readiness, scalability, and clarity of the demo pitch.',
      maxScore: 25,
      weightPercentage: 25,
      requiredEvidence: '2-minute video walkthrough and slide deck',
    },
  ],
};

export const seedTasks = [
  {
    _id: IDS.tasks[0],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.rahul,
    ownerName: 'Rahul Sharma',
    title: 'Build Authentication & Role Switcher UI',
    description: 'Implement simple clean login screen and quick demo role selection bar.',
    status: 'done',
    priority: 'high',
    tag: 'Frontend',
    targetDate: new Date('2026-10-12T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[1],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.ananya,
    ownerName: 'Ananya Iyer',
    title: 'Design Student Dashboard Wireframes',
    description: 'Figma wireframes with clear hierarchy for syllabus progress and study cards.',
    status: 'done',
    priority: 'medium',
    tag: 'Design',
    targetDate: new Date('2026-10-12T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[2],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.vivek,
    ownerName: 'Vivek Patel',
    title: 'Implement Syllabus Extraction & Ingestion Pipeline',
    description: 'Ingest syllabus PDF texts and chunk into structured topic vectors.',
    status: 'done',
    priority: 'high',
    tag: 'AI/RAG',
    targetDate: new Date('2026-10-13T12:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[3],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.karthik,
    ownerName: 'Karthik',
    title: 'Create REST API for Topic Quiz Generation',
    description: 'Express routes for creating customized diagnostic tests and tracking attempts.',
    status: 'in_progress',
    priority: 'high',
    tag: 'Backend',
    targetDate: new Date('2026-10-13T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[4],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.rahul,
    ownerName: 'Rahul Sharma',
    title: 'Develop Interactive Question Card UI',
    description: 'Quiz card component with instant feedback, explanations, and score tracking.',
    status: 'in_progress',
    priority: 'medium',
    tag: 'Frontend',
    targetDate: new Date('2026-10-13T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[5],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.karthik,
    ownerName: 'Karthik',
    title: 'Setup MongoDB Schema & Indexing',
    description: 'User progress collections, topic completion indexes, and quiz submission schemas.',
    status: 'done',
    priority: 'high',
    tag: 'Database',
    targetDate: new Date('2026-10-12T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[6],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.vivek,
    ownerName: 'Vivek Patel',
    title: 'Integrate LLM Flashcard Summary Prompts',
    description: 'Refine prompt engineering for 3-bullet concept summaries per syllabus section.',
    status: 'in_progress',
    priority: 'medium',
    tag: 'AI/RAG',
    targetDate: new Date('2026-10-13T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[7],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.karthik,
    ownerName: 'Karthik',
    title: 'Deploy Backend API to Cloud (Render)',
    description: 'Resolve SSL handshake and CORS policy issue on staging instance.',
    status: 'blocked',
    priority: 'high',
    tag: 'DevOps',
    targetDate: new Date('2026-10-14T12:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[8],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.ananya,
    ownerName: 'Ananya Iyer',
    title: 'Record 2-Minute Product Demo Walkthrough',
    description: 'Screen capture key user flow: syllabus upload -> dynamic roadmap -> diagnostic quiz.',
    status: 'todo',
    priority: 'high',
    tag: 'Submission',
    targetDate: new Date('2026-10-14T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[9],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.rahul,
    ownerName: 'Rahul Sharma',
    title: 'Finalize Slide Deck & Problem Impact PPT',
    description: 'Compile 6-slide presentation summarizing problem, tech stack, architecture, and roadmap.',
    status: 'todo',
    priority: 'medium',
    tag: 'Submission',
    targetDate: new Date('2026-10-14T18:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[10],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.ananya,
    ownerName: 'Ananya Iyer',
    title: 'Run End-to-End Responsive Testing',
    description: 'Validate dashboard responsiveness on mobile devices and tablet breakpoints.',
    status: 'todo',
    priority: 'low',
    tag: 'QA',
    targetDate: new Date('2026-10-14T20:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
  {
    _id: IDS.tasks[11],
    eventId: IDS.event,
    teamId: IDS.team,
    ownerId: IDS.users.karthik,
    ownerName: 'Karthik',
    title: 'Review Rulebook Submission Checklist',
    description: 'Verify all mandatory deliverables (repo, live link, video, slide deck) conform to rules.',
    status: 'todo',
    priority: 'high',
    tag: 'Submission',
    targetDate: new Date('2026-10-14T21:00:00.000Z'),
    version: 1,
    createdBy: IDS.users.karthik,
  },
];

export const seedMilestones = [
  {
    _id: IDS.milestones[0],
    eventId: IDS.event,
    teamId: IDS.team,
    title: 'Project Setup & Design Tokens',
    description: 'Team sync, GitHub repo initialized, design system components created.',
    dueDate: new Date('2026-10-12T18:00:00.000Z'),
    status: 'completed',
    completionPercentage: 100,
  },
  {
    _id: IDS.milestones[1],
    eventId: IDS.event,
    teamId: IDS.team,
    title: 'Database Schema & Ingestion API',
    description: 'Database models designed, initial syllabus parsing prototype tested.',
    dueDate: new Date('2026-10-12T23:59:00.000Z'),
    status: 'completed',
    completionPercentage: 100,
  },
  {
    _id: IDS.milestones[2],
    eventId: IDS.event,
    teamId: IDS.team,
    title: 'Core UI Flow & AI Pipeline',
    description: 'Building question cards, hooking up LLM flashcard generation.',
    dueDate: new Date('2026-10-13T18:00:00.000Z'),
    status: 'in_progress',
    completionPercentage: 60,
  },
  {
    _id: IDS.milestones[3],
    eventId: IDS.event,
    teamId: IDS.team,
    title: 'Backend Deployment & Testing',
    description: 'Unblock staging API deployment and test full end-to-end flow.',
    dueDate: new Date('2026-10-14T12:00:00.000Z'),
    status: 'pending',
    completionPercentage: 20,
  },
  {
    _id: IDS.milestones[4],
    eventId: IDS.event,
    teamId: IDS.team,
    title: 'Demo Video & Final Submission',
    description: 'Screen recording demo, slide deck completion, and official submission.',
    dueDate: new Date('2026-10-14T23:59:00.000Z'),
    status: 'pending',
    completionPercentage: 0,
  },
];

export const seedSubmission = {
  _id: IDS.submission,
  eventId: IDS.event,
  teamId: IDS.team,
  challengeId: IDS.challenges.studyEngine,
  rubricVersion: 1,
  description: 'Intelligent adaptive syllabus roadmap and automated quiz diagnostic platform.',
  repositoryUrl: 'https://github.com/karthik-dev/ai-study-planner',
  deploymentUrl: 'https://study-planner-demo.vercel.app',
  demoVideoUrl: 'https://youtube.com/watch?v=demo-karthik',
  presentationUrl: 'https://docs.google.com/presentation/d/mock-slides',
  evidence: [
    {
      criterionId: 'crit_technical',
      type: 'githubRepo',
      url: 'https://github.com/karthik-dev/ai-study-planner',
      notes: 'Clean Node.js & LangChain architecture with 85% test coverage',
    },
    {
      criterionId: 'crit_ux',
      type: 'deploymentLink',
      url: 'https://study-planner-demo.vercel.app',
      notes: 'Production build hosted on Vercel',
    },
    {
      criterionId: 'crit_impact',
      type: 'demoVideo',
      url: 'https://youtube.com/watch?v=demo-karthik',
      notes: '2-minute walkthrough covering student workflow',
    },
    {
      criterionId: 'crit_impact',
      type: 'presentationDeck',
      url: 'https://docs.google.com/presentation/d/mock-slides',
      notes: '6-slide deck',
    },
  ],
  checklist: {
    githubRepo: true,
    deploymentLink: true,
    projectDescription: true,
    presentationDeck: true,
    demoVideo: true,
    finalTesting: true,
  },
  readinessPercentage: 100,
  status: 'submitted',
  revision: 1,
  submittedAt: new Date('2026-10-14T20:30:00.000Z'),
};

export const seedReputations = [
  {
    userId: IDS.users.karthik,
    eventId: IDS.event,
    points: 1000,
    type: 'PLACEMENT',
    reason: 'Built CodeMentor AI. Highest architectural score across 120 collegiate teams.',
    createdAt: new Date('2025-12-20T10:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    eventId: IDS.event,
    points: 150,
    type: 'PLACEMENT',
    reason: 'Qualified for national finals round in Smart Agriculture category.',
    createdAt: new Date('2025-10-15T10:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    eventId: IDS.event,
    points: 100,
    type: 'PARTICIPATION',
    reason: 'Completed project submission within deadline with working live demo.',
    createdAt: new Date('2025-08-10T10:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    eventId: IDS.event,
    points: 15,
    type: 'TASK_COMPLETION',
    reason: 'Closed critical database and API sprint tasks ahead of schedule.',
    createdAt: new Date('2026-10-12T16:00:00.000Z'),
  },
];

export const seedNotifications = [
  {
    userId: IDS.users.karthik,
    type: 'team',
    title: 'Invitation Accepted',
    message: 'Rahul Sharma accepted your team invitation for Team Nova.',
    relatedEntity: 'Team',
    relatedEntityId: IDS.team,
    link: '/team',
    isRead: false,
    createdAt: new Date('2026-10-12T11:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    type: 'deadline',
    title: 'Submission Approaching',
    message: 'NexusHack 2026 submission closes in 28 hours (Oct 14 · 11:59 PM).',
    relatedEntity: 'Event',
    relatedEntityId: IDS.event,
    link: '/team/submission',
    isRead: false,
    createdAt: new Date('2026-10-13T18:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    type: 'feedback',
    title: 'Mentor Feedback Received',
    message: 'Dr. Arvind Rao reviewed your AI Quiz generation module.',
    relatedEntity: 'Team',
    relatedEntityId: IDS.team,
    link: '/team/feedback',
    isRead: true,
    createdAt: new Date('2026-10-13T14:00:00.000Z'),
  },
  {
    userId: IDS.users.karthik,
    type: 'reputation',
    title: 'Reputation Updated',
    message: 'You earned +15 reputation for completing 4 core backend tasks.',
    link: '/reputation',
    isRead: true,
    createdAt: new Date('2026-10-12T16:00:00.000Z'),
  },
];

export const seedFeedback = [
  {
    eventId: IDS.event,
    teamId: IDS.team,
    mentorId: IDS.users.arvind,
    mentorName: 'Dr. Arvind Rao',
    mentorRole: 'Faculty Mentor · AI & Distributed Systems',
    rating: 4.5,
    title: 'Promising RAG Flow, Watch Out for Vector Search Latency',
    message: 'The syllabus ingestion pipeline is well-structured. For the live jury evaluation, make sure you cache the generated diagnostic quiz questions in Redis or memory so judges do not experience a 4-5 second model inference lag during demo.',
    blocker: 'Staging Render deployment SSL/CORS setup',
    recommendations: [
      'Add a fast fallback cache for the sample syllabus files',
      'Include a visual indicator showing the exact source textbook chunk',
      'Keep the demo presentation concise on the actual user problem solved',
    ],
  },
];

export const seedScore = {
  eventId: IDS.event,
  submissionId: IDS.submission,
  judgeId: IDS.users.siddharth,
  judgeName: 'Siddharth Sen',
  rubricVersion: 1,
  criteriaScores: [
    { criterionId: 'crit_innovation', criterionName: 'Innovation & Originality', score: 22, maxScore: 25 },
    { criterionId: 'crit_technical', criterionName: 'Technical Execution', score: 28, maxScore: 30 },
    { criterionId: 'crit_ux', criterionName: 'UI/UX & Accessibility', score: 18, maxScore: 20 },
    { criterionId: 'crit_impact', criterionName: 'Impact & Feasibility', score: 23, maxScore: 25 },
  ],
  totalScore: 91,
  comments: 'Outstanding architecture, clean LangChain ingestion pipeline, and clear problem impact.',
};

export const seedDocument = {
  _id: IDS.document,
  eventId: IDS.event,
  title: 'NexusHack 2026 Official Rulebook & Guidelines',
  version: '2.0',
  sourceType: 'pdf',
  sourceUrl: 'https://nexushack.org/assets/rulebook-v2.pdf',
  fileSize: 1048576,
  status: 'ready',
  uploadedBy: IDS.users.aakash,
};

export const seedChunks = [
  {
    documentId: IDS.document,
    eventId: IDS.event,
    version: '2.0',
    page: 1,
    section: '1.0 Eligibility & Teams',
    text: 'Open to all enrolled undergraduate and postgraduate students. Teams must consist of 2 to 4 members. Inter-college teams are permitted for online tracks.',
    embedding: [0.012, -0.045, 0.089, 0.124], // sample vector prefix
    embeddingModel: 'text-embedding-004',
  },
  {
    documentId: IDS.document,
    eventId: IDS.event,
    version: '2.0',
    page: 2,
    section: '2.0 Original Work',
    text: 'All code must be authored during the 48-hour sprint. Open source libraries, SDKs, and pre-trained weights are allowed provided they are declared in the README.',
    embedding: [0.034, -0.012, 0.055, 0.098],
    embeddingModel: 'text-embedding-004',
  },
  {
    documentId: IDS.document,
    eventId: IDS.event,
    version: '2.0',
    page: 3,
    section: '3.0 Technology Restrictions',
    text: 'No paid proprietary backends without public tier. Teams may use free tier APIs, open-source models (Ollama, HuggingFace), and public cloud credits.',
    embedding: [-0.021, 0.076, 0.043, 0.112],
    embeddingModel: 'text-embedding-004',
  },
  {
    documentId: IDS.document,
    eventId: IDS.event,
    version: '2.0',
    page: 4,
    section: '4.0 Deliverables',
    text: 'Public GitHub repository with MIT/Apache license, working deployed demo link, 2-minute demonstration video, and slide deck.',
    embedding: [0.065, -0.033, 0.091, 0.078],
    embeddingModel: 'text-embedding-004',
  },
];

export const seedAgentRun = {
  _id: IDS.agentRun,
  eventId: IDS.event,
  teamId: IDS.team,
  requestedBy: IDS.users.karthik,
  question: 'Can our team finish and submit before the Sunday deadline?',
  status: 'proposed',
  toolsUsed: ['taskVelocityEstimator', 'criticalPathScheduler', 'blockerAnalyzer'],
  proposal: {
    canFinishBeforeDeadline: true,
    confidencePercentage: 88,
    assessment: 'Your team has completed 72% of milestones and is in a strong position. The critical path involves resolving the Render deployment blocker and recording the 2-minute demo video.',
    criticalBlocker: 'Backend Render deployment SSL/CORS issue (Task #8)',
    recommendations: [
      'Reassign deployment support to Karthik & Rahul this evening.',
      'Ananya to record demo script walkthrough Saturday afternoon once deployment passes.',
      'Conduct final judging checklist review 4 hours before cutoff.',
    ],
    proposedSchedule: [
      { time: 'Saturday 4:00 PM', task: 'Resolve Render backend CORS & verify API endpoints' },
      { time: 'Saturday 8:00 PM', task: 'Freeze frontend features and trigger production Vercel build' },
      { time: 'Sunday 10:00 AM', task: 'Record 2-minute product demo walkthrough' },
      { time: 'Sunday 4:00 PM', task: 'Complete submission checklist and submit project' },
    ],
  },
};
